Models/Review.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace eCommerce.Models
{
    public class Review
    {
        public Guid Id { get; set; }
        public Guid SellerUserId { get; set; }
        public int Score { get; set; }
        public string Text { get; set; }
        public Guid UserId { get; set; }
        public DateTime DateCreated { get; set; }
        public string DisplayName { get; set; }
    }
}

Controllers/AdController.cs
using eCommerce.Data;
using eCommerce.Models;
using eCommerce.Models.Resources;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eCommerce.Controllers
{
    public class AdController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;
        public AdController(UserManager<ApplicationUser> userManager, ApplicationDbContext context, IWebHostEnvironment env)
        {
            _userManager = userManager;
            _context = context;
            _env = env;
        }

        // GET: AdController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Map()
        {
            return View();
        }

        // GET: AdController/Details/5
        public async Task<ActionResult> Details(Guid id)
        {
            var viewModel = new AdDetailsViewModel();
            viewModel.Ad = _context.Ad.Include(ad => ad.AdImages).FirstOrDefault(ad => ad.Id == id);
            if (viewModel.Ad != null)
            {
                var user = await _userManager.GetUserAsync(User);
                var author = await _userManager.FindByIdAsync(viewModel.Ad.UserId.ToString());
                viewModel.AuthorName = author.UserName;
                viewModel.CanDelete = user != null && (viewModel.Ad.UserId.ToString() == user.Id || await _userManager.IsInRoleAsync(user, "Admin"));
                viewModel.CanEdit = user != null && (viewModel.Ad.UserId.ToString() == user.Id);
            }
            return View(viewModel);
        }

        // GET: AdController/Create
        [Authorize(Roles = "User")]
        public ActionResult Create()
        {
            var userId = _userManager.GetUserId(User);
            var userProfile = _context.UserProfile.FirstOrDefault(up => up.UserId.ToString() == userId);
            if (userProfile == null)
            {
                TempData["StatusMessage"] = "Please complete your profile before posting an ad.";
                return LocalRedirect("/Identity/Account/Manage");
            }
            var viewModel = new CreateAdViewModel();
            return View(viewModel);
        }

        // POST: AdController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateAdViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Ad
                    var newAd = model.NewAd;
                    var user = await _userManager.GetUserAsync(User);
                    if (int.TryParse(model.NewAd.City, out int cityInt))
                    {
                        var cityEnum = (CitiesEnum)cityInt;
                        var city = EnumHelpers.GetEnumDisplayName(cityEnum);
                        newAd.City = city;
                    }
                    else
                    {
                        newAd.City = null;
                    }
                    newAd.UserId = Guid.Parse(user.Id);
                    newAd.DateCreated = DateTime.UtcNow;
                    _context.Add(newAd);
                    _context.SaveChanges();

                    // Ad image
                    if (model.Picture != null)
                    {
                        var fileName = UploadedFile(model);
                        var adImage = new AdImage();
                        adImage.AdId = newAd.Id;
                        adImage.DateCreated = DateTime.UtcNow;
                        adImage.ImagePath = "~/images/" + fileName;
                        adImage.UserId = Guid.Parse(user.Id);
                        _context.Add(adImage);
                        _context.SaveChanges();
                    }

                    return RedirectToAction(nameof(Details), new { id = newAd.Id });
                }
                return View();
            }
            catch (Exception e)
            {
                var test = e;
                return View();
            }
        }

        private string UploadedFile(CreateAdViewModel model)
        {
            if (model.Picture != null)
            {
                var uploadsFolder = Path.Combine(_env.WebRootPath, "images");
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }
                var uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Picture.FileName;
                var filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Picture.CopyTo(fileStream);
                }
                return uniqueFileName;
            }
            return string.Empty;
        }

        [Authorize(Roles = "User")]
        // GET: AdController/Edit/5
        public async Task<ActionResult> Edit(Guid id)
        {
            var viewModel = new CreateAdViewModel();
            var ad = _context.Ad.Include(ad => ad.AdImages).FirstOrDefault(ad => ad.Id == id);
            var user = await _userManager.GetUserAsync(User);
            if (ad != null && ad.UserId.ToString() == user.Id)
            {
                viewModel.NewAd = ad;
                return View(viewModel);
            }
            Response.StatusCode = 403;
            return View();
        }

        // POST: AdController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Edit(Guid id, CreateAdViewModel model)
        {
            try
            {
                var ad = _context.Ad.Include(ad => ad.AdImages).FirstOrDefault(ad => ad.Id == id);
                var adUpdate = model.NewAd;
                var user = await _userManager.GetUserAsync(User);
                if (ad.UserId == Guid.Parse(user.Id))
                {
                    ad.DateUpdated = DateTime.UtcNow;
                    ad.Title = adUpdate.Title;
                    ad.Description = adUpdate.Description;
                    if (int.TryParse(adUpdate.City, out int cityInt))
                    {
                        var cityEnum = (CitiesEnum)cityInt;
                        var city = EnumHelpers.GetEnumDisplayName(cityEnum);
                        ad.City = city;
                    }
                    else
                    {
                        ad.City = null;
                    }
                    ad.Category = adUpdate.Category;
                    ad.Price = adUpdate.Price;

                    // Ad image
                    if (model.Picture != null)
                    {
                        var fileName = UploadedFile(model);
                        var adImage = new AdImage();
                        adImage.AdId = ad.Id;
                        adImage.DateCreated = DateTime.UtcNow;
                        adImage.ImagePath = "~/images/" + fileName;
                        adImage.UserId = Guid.Parse(user.Id);
                        _context.RemoveRange(ad.AdImages);
                        _context.Add(adImage);
                        _context.SaveChanges();
                    }

                    _context.SaveChanges();
                    return RedirectToAction(nameof(Details), new { id = ad.Id });
                }
                else
                    return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User, Admin")]
        public async Task<ActionResult> Delete(Guid Id)
        {
            try
            {
                var ad = _context.Ad.Include(ad => ad.AdImages).FirstOrDefault(ad => ad.Id == Id);
                var user = await _userManager.GetUserAsync(User);
                if (ad != null && (ad.UserId.ToString() == user.Id || await _userManager.IsInRoleAsync(user, "Admin")))
                {
                    if (ad.AdImages.Any())
                        ad.AdImages.ForEach(image => {
                            _context.Remove(image);
                        });
                    _context.Remove(ad);
                    _context.SaveChanges();
                }
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/UserController.cs
using eCommerce.Data;
using eCommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eCommerce.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        public UserController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: UserController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Chat()
        {
            return View();
        }

        // GET: UserController/Details/5
        public ActionResult Details(Guid id)
        {
            var viewModel = new SellerDetailsViewModel();
            viewModel.UserProfile = _context.UserProfile.FirstOrDefault(up => up.UserId == id) ?? new UserProfile();
            viewModel.Ads = _context.Ad.Include(ad => ad.AdImages).Where(a => a.UserId == id).ToList();
            var userId = _userManager.GetUserId(User);
            viewModel.ShowFollowButton = !string.IsNullOrEmpty(userId) && userId != viewModel.UserProfile.UserId.ToString();
            viewModel.IsFollowing = viewModel.ShowFollowButton && _context.Followers.Any(f => f.UserId.ToString() == userId && f.SellerUserId == viewModel.UserProfile.UserId);
            var reviews = _context.Reviews.Where(r => r.SellerUserId == id).ToList();
            if (reviews.Any())
            {
                var averageScore = reviews.Average(r => r.Score);
                viewModel.ShowReviewScore = true;
                viewModel.ReviewScore = Math.Round(averageScore * 2, MidpointRounding.AwayFromZero) / 2;
            }

            return View(viewModel);
        }

        public async Task<ActionResult> ToggleFollow(Guid id)
        {
            var userId = _userManager.GetUserId(User);
            if (userId != id.ToString())
            {
                var seller = await _userManager.FindByIdAsync(id.ToString());
                if (seller != null)
                {
                    var follower = _context.Followers.FirstOrDefault(f => f.UserId.ToString() == userId && f.SellerUserId.ToString() == seller.Id);
                    if (follower != null)
                    {
                        _context.Remove(follower);
                    }
                    else
                    {
                        var newFollower = new Follower();
                        newFollower.UserId = Guid.Parse(userId);
                        newFollower.SellerUserId = Guid.Parse(seller.Id);
                        newFollower.DateCreated = DateTime.UtcNow;
                        _context.Add(newFollower);
                    }
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Details", new { id });
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Reviews(Guid id)
        {
            var viewModel = new ReviewsViewModel();
            viewModel.UserProfile = _context.UserProfile.FirstOrDefault(up => up.UserId == id);
            viewModel.SellerUserId = id;
            viewModel.Reviews = _context.Reviews.Where(r => r.SellerUserId == id).ToList();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Reviews(Guid id, IFormCollection collection)
        {
            if (int.TryParse(collection["stars"], out int score))
            {
                var newReview = new Review();
                newReview.Score = score;
                newReview.Text = collection["text"];
                newReview.SellerUserId = id;
                newReview.UserId = Guid.Parse(_userManager.GetUserId(User));
                newReview.DateCreated = DateTime.UtcNow;

                var userProfile = _context.UserProfile.FirstOrDefault(up => up.UserId == newReview.UserId);
                if (userProfile != null)
                    newReview.DisplayName = userProfile.Name;
                else
                    newReview.DisplayName = "Anonymous";

                _context.Add(newReview);
                _context.SaveChanges();
            }

            return RedirectToAction("Reviews", new { id });
        }
    }
}

Views/User/Chat.cshtml
@page
<div class="row">
    <div class="col-6">
        <ul id="messagesList"></ul>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <hr />
    </div>
</div>
<div class="msg-container" width="100%">
    <div class="form-field">
        <div class="row" style="display:none;">
            <label class="col-sm-2 col-form-label">User</label>
            <div class="col-sm-10">
                <input type="text" id="userInput" value="@User.Identity.Name" disabled="disabled" />
            </div>
        </div>
         <div class="row">
           <label class="col-sm-2 col-form-label">Message</label>
            <div class="col-sm-10">
                <input type="text" id="messageInput" />
            </div>
        </div>
    </div>
    <div class="msg-row">
        <div class="row">
            <input type="button" id="sendButton" value="Send Message" />
        </div>
    </div>
</div>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

Views/User/Details.cshtml
@model SellerDetailsViewModel
@{
    ViewData["Title"] = "Seller Details";
}

<div class="main-wrapper text-center">
    <section class="section about-section gray-bg" id="about">
        <div class="container">
            <div class="row align-items-left flex-row-reverse">
                <div class="col-lg-6">
                    @if (Model.ShowFollowButton)
                    {
                    <form asp-controller="User" asp-action="ToggleFollow" asp-route-id="@Model.UserProfile.UserId">
                    <button class="follow-btn btn-primary btn @(Model.IsFollowing ? "btn-secondary" : "btn-primary")" onclick="toggleFollow()">@(Model.IsFollowing ? "Unfollow" : "Follow")</button>
                    </form>
                    }
                    <div class="about-text go-to text-left">
                        <h3 class="mb-3">Seller Profile</h3>
                        <button class="map-btn mb-3" onclick="showMap()">
                            <p class="grey-text">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                                    <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z" />
                                </svg>
                                @Model.UserProfile.City
                            </p>
                        </button>
                        <div id="mapDiv mb-3" style="display:none">
                            <div class="gmap_canvas">
                                <iframe width="100%" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=@(Model.UserProfile.City)&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
                                </iframe>
                                <style>
                                    .mapouter {
                                        position: relative;
                                        text-align: right;
                                        height: 500px;
                                        width: 100%;
                                    }
                                </style>
                                <a href="https://www.embedgooglemap.net">embedgooglemap.net</a>
                                <style>
                                    .gmap_canvas {
                                        overflow: hidden;
                                        background: none !important;
                                        height: 500px;
                                        width: 100%;
                                    }
                                </style>
                            </div>
                        </div>
                        <h4 class="mb-3">Details</h4>
                        <div class="row about-list mb-3">
                            <div class="col-md-12">
                                <div class="media">
                                    <label>Name</label>
                                    <p>@Model.UserProfile.Name</p>
                                </div>
                                <div class="media">
                                    <label>Phone</label>
                                    <p>@Model.UserProfile.PhoneNumber</p>
                                </div>
                                <div class="media">
                                    <label>Email</label>
                                    <p>@Model.UserProfile.Email</p>
                                </div>
                            </div>
                        </div>
                        <h4 class="mb-3">Bio</h4>
                        <p align="left">@Model.UserProfile.Bio</p>
                    </div>
                    <a asp-controller="User" asp-action="Reviews" asp-route-id="@Model.UserProfile.UserId" class="btn btn-primary">View Reviews</a>
                    @if (Model.ShowReviewScore)
                    {
                    <div class="str-rating">
                        <span class="fa @(Model.ReviewScore > 0 ? (Model.ReviewScore == 0.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
                        <span class="fa @(Model.ReviewScore > 1  ? (Model.ReviewScore == 1.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
                        <span class="fa @(Model.ReviewScore > 2 ? (Model.ReviewScore == 2.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
                        <span class="fa @(Model.ReviewScore > 3 ? (Model.ReviewScore == 3.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
                        <span class="fa @(Model.ReviewScore > 4 ? (Model.ReviewScore == 4.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
                    </div>
                    }
                </div>
                <div class="col-lg-6">
                    <div class="about-avatar">
                        <img style="border-radius: 30px; width: 100%" src="@Model.UserProfile.ProfilePic" asp-append-version="true" alt="Profile Picture">
                    </div>
                </div>
            </div>

            <div class="counter">
                <h3>User Ads</h3>
                <div class="row">
                    @foreach (var ad in Model.Ads)
                    {
                        <div class="col-md-4">
                            <a asp-controller="Ad" asp-action="Details" asp-route-id="@ad.Id">
                                <div class="card mb-4 box-shadow h-100 d-flex flex-column" style="margin-bottom: 10px">
                                    <img class="bd-placeholder-img card-img-top" src="@(ad.AdImages.Any() ? ad.AdImages[0].ImagePath : "~/img/default.jpg")" asp-append-version="true" width="100" height="200" />
                                    <div class="card-body" style="padding: 1.25rem 1.25rem 0rem 1.25rem">
                                        <p align="left">
                                            <span class="badge @(ad.IsBuying ? "badge-info" : "badge-success")">@(ad.IsBuying ? "Buying" : "Selling")</span>
                                        </p>
                                        <h5 class="prod-title" align="left">@ad.Title</h5>
                                        <p class="price" align="left">Price: @ad.Price.ToString("c")</p>
                                        <p class="grey-text" align="right">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                                                <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z" />
                                            </svg>
                                            @ad.City
                                        </p>
                                        <!-- Description with limited height -->
                                        <p class="card-text flex-grow-1" style="overflow: hidden; max-height: 60px;">
                                            @ad.Description
                                        </p>
                                        <p style="color:dimgray; margin-bottom: 0px;" align="right">more...</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</div>

@section Scripts {
    <script type="text/javascript">
        function showMap() {
            var x = document.getElementById("mapDiv");
            if (x.style.display == "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }

        @*function toggleFollow() {
            $.ajax({
                type: "POST",
                url: "@Url.Action("toggleFollow", "User")"
            });
        }*@
    </script>

}

Views/User/Reviews.cshtml
@model ReviewsViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@{
    ViewData["Title"] = "Reviews";
}
<div class="main-wrapper text-center">
    @if (SignInManager.IsSignedIn(User))
    {
        <div class="card">
            <div class="card-header">Leave a Review</div>
            <div class="card-body">
                <form asp-controller="User" asp-action="Reviews" asp-route-id="@Model.SellerUserId">
                    <div class="rating">
                        <label>
                            <input type="radio" name="stars" value="1" required />
                            <span class="icon">★</span>
                        </label>
                        <label>
                            <input type="radio" name="stars" value="2" />
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                        </label>
                        <label>
                            <input type="radio" name="stars" value="3" />
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                        </label>
                        <label>
                            <input type="radio" name="stars" value="4" />
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                        </label>
                        <label>
                            <input type="radio" name="stars" value="5" />
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                            <span class="icon">★</span>
                        </label>
                    </div>
                    <br />
                    <textarea name="text" maxlength="500" required></textarea>
                    <br />
                    <button type="submit">Post Review</button>
                </form>
            </div>
        </div>
    }
    <h2>Reviews</h2>
    <hr style="width:50%; color: grey;">
    @if (Model.Reviews == null || Model.Reviews.Count == 0)
    {
        <h4>This seller has no reviews.</h4>
    } 
    @foreach (var review in Model.Reviews)
    {
        <div class="str-rating">
            <span class="fa @(review.Score > 0 ? (review.Score == 0.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
            <span class="fa @(review.Score > 1  ? (review.Score == 1.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
            <span class="fa @(review.Score > 2 ? (review.Score == 2.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
            <span class="fa @(review.Score > 3 ? (review.Score == 3.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
            <span class="fa @(review.Score > 4 ? (review.Score == 4.5 ? "fa-star-half-o" : "fa-star") : "fa-star-o")"></span>
        </div>
        <div class="card-subtitle mb-2 text-muted">@review.DisplayName</div>
        <p class="card-text">@review.Text</p>
        if (Model.Reviews.IndexOf(review) != Model.Reviews.Count - 1)
        {
            <hr style="width:50%; color: grey;">
        }
    }
</div>